baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Jonathan Yudi Gunawan - Personal Website'
theme = 'PaperMod'

[params]
description = "A personal website of Jonathan Yudi Gunawan"
author = "Jonathan Yudi Gunawan"
